select distinct(N_NAME),sum(L_QUANTITY) AS CONTAGEM 
FROM NATION INNER JOIN CUSTOMER ON N_NATIONKEY= C_NATIONKEY INNER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY INNER JOIN LINEITEM on L_ORDERKEY=O_ORDERKEY  
GROUP BY N_NATIONKEY 
HAVING CONTAGEM>62000
ORDER BY CONTAGEM DESC;